### ISSUE TITLE
Upgrade Secp256k1

### ISSUE THREAD

**Issue by driftluo** [cryptape/cita-cli#100]
Update the algorithm library, relying on the original address：
```toml
secp256k1 = "0.12.2"
```

**Comment by lancelot96** [comment]
Just need to replace `eth-secp256k1` by `secp256k1` and make sure all tests will pass?

**Comment by driftluo** [comment]
No, the test need to be modified because it thinks that all zero massage is invalid data, you can directly view the source code of secp256k1

https://github.com/cryptape/cita-cli/blob/2fef9295cee5edbc775f329ce1107c70942db569/cita-tool/src/crypto/cita_secp256k1.rs#L248
