### ISSUE TITLE
sendRawTransaction support `--to` param

### ISSUE THREAD

**Issue by kaikai1024** [cryptape/cita-cli#20]

**Comment by driftluo** [comment]
`to` means contract address，`sendrawTransaction` has `--address` param is the contract address ，default "0x"

**Comment by kaikai1024** [comment]
ok.  I did't run '--help'. only chekc `the USAGE:
    cita-cli rpc sendRawTransaction --code <code> --height <height> --private-key <private-key>
`

**Comment by TheWaWaR** [comment]
@kaikai1024  Only **required** arguments show in `USAGE`
