### ISSUE TITLE
Change parameter `fromBlock` to `"0x0"`

### ISSUE THREAD

**Issue by keroro520** [cryptape/cita-cli#70]
Notice that the subcommand `getLogs` has a parameter "--from", which default is `"latest"`. Here I think `"0x0"` as default value is better than `"latest"`, cause users use this command to search logs along the whole history, but not just only from latest block. More ever, the latest block is changing.

code here: https://github.com/cryptape/cita-cli/blob/master/cita-tool/src/client/basic.rs#L548

**Comment by TheWaWaR** [comment]
We better stick to [ethereum wiki](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getlogs).

**Comment by driftluo** [comment]
On [doc](https://docs.nervos.org/cita/#/rpc_guide/rpc-types), the default value of the type `Quantity | BlockTag` declaration is `latest`
> Quantity | BlockTag ： 通常可以为空，为空时默认值为 "latest" 。
