### ISSUE TITLE
host or url?

### ISSUE THREAD

**Issue by u2** [cryptape/cita-cli#80]
```
switch --host 47.97.191.27:1337
[       url        ]: 47.97.191.27:1337
```
This makes me confused. I think `url` is better.

**Comment by u2** [comment]
```
switch --host 47.97.191.27:1337
[       url        ]: 47.97.191.27:1337
```

```
cita> scm SysConfig setChainName --chain-name AAA --admin-private 0x5f0258a4778057a8a7d97809bd209055b2fbafa654ce7d31ec7191066b9225e6
>> Hyper error: client requires absolute-form URIs
```

**Comment by TheWaWaR** [comment]
I agree, the url should be full format: `http://47.97.191.27:1337`

**Comment by driftluo** [comment]
It does cause confusion here. 

Whether url should complete `http://` is also controversial. If it is not complete, it means that there is a default behavior of adding `http://`, which will lead to confusion.
